### ISSUE TITLE
Gather features and deprecations for Ember 3.21 release

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#43]
## Background

The app is able to show features and deprecations by reading Markdown files in the `source` directory. When a new version of Ember is released (for example, version 3.21), we need to generate Markdown files and provide relevant information.

## Problem

Currently, the app doesn't show features and deprecations that were added to Ember.js, Ember Data, and Ember CLI in version 3.21.

- https://upgrade-guide.netlify.app/?fromVersion=3.20

## TODOs

- [ ] Use Ember CLI to generate skeleton Markdown files for Ember.js, Ember Data, and Ember CLI.

- [ ] List features and deprecations (if they exist) for Ember.js.

- [ ] List features and deprecations (if they exist) for Ember Data.

- [ ] List features and deprecations (if they exist) for Ember CLI.

- [ ] Run the app locally to check that we can see features and deprecations when we select `3.21` for `To version`.

## References

- [Ember Blog - 3.21 Release](https://blog.emberjs.com/2020/09/02/ember-3-21-released.html)
- [README - Code Generators](https://github.com/ember-learn/upgrade-guide/blob/45794a45e6676e7598f12e4b47a6cdd151b17149/README.md#adding-the-latest-ember-version)

**Comment by Pustur** [comment]
I can take this as well 👍

**Comment by ijlee2** [comment]
Hi, @Pustur. I appreciate your energy in helping out with Ember repos!

I want to make sure that there are enough issues for many people to work on during Hacktoberfest and the upcoming EmberFest workshop. (Coming up with an issue and writing it up is not easy...)

Let me ask you to work on #50 for now. If no one else can volunteer for this issue, I will ping you to see if you can still help!

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by Shridhar1810** [comment]
Should  take this

**Comment by ijlee2** [comment]
Hi, @Shridhar1810. Thanks for your interest in helping out with the Upgrades Guide! If you have questions, feel free to reach out by commenting in this issue, or over the `#hacktoberfest` channel at [Ember Discord].
