### ISSUE TITLE
Componentize the Ember Versions form (Part 1 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#44]
## Background

In the homepage, a user can describe their app by selecting `fromVersion` and `toVersion` in the `Ember Versions` form.

## Problem

Currently, the `<form>` element lives in the route template `app/templates/index.hbs`.

The form is rather large (adds ~40 lines of code to `index.hbs`), requires that we store code for updating state in the `index` controller (a singleton), and makes it hard to separate the form state from URL state (query parameters).

### Part 1: Create `<EmberVersionsForm>` component

- [ ] Use Ember CLI to generate a component called `<EmberVersionsForm>`, along with the backing class. You should also see a test file in the `tests/integration/components` directory.

    Keep in mind that the component will receive 1 argument: `@onSubmit`, a callback function that receives `fromVersion` and `toVersion` as a hash (POJO).

- [ ] Copy-paste the form and relevant class code from the `index` route to the component.

    ```javascript
    // app/components/ember-versions-form.js

    versions = VERSIONS;
    @tracked fromVersion = '3.15';
    @tracked toVersion = VERSIONS[VERSIONS.length - 1];

    @action doNotSubmitForm(event) { ... }
    @action updateFromVersion(event) { ... }
    @action updateToVersion(event) { ... }
    ```

- [ ] Rename the action `doNotSubmitForm` to `submitForm`. In addition to `event.preventDefault`, it should call `@onSubmit` (if the callback function exists) and pass the form state `fromVersion` and `toVersion` in a hash (POJO).

- [ ] For now (this behavior will change in another issue), we want to call `submitForm` when the user changes the select option. Modify `updateFromVersion` and `updateToVersion` so that they will call `submitForm`.

- [ ] Last but not least, write rendering tests to describe how the form should behave. Please write tests to check the following:

    - Initially, the form shows `3.15` and the latest version for `fromVersion` and `toVersion`.
    - We can submit the form by changing `fromVersion`. In addition to asserting that we see the correct select option, assert that `@onSubmit` is called and receives the new values of `fromVersion` and `toVersion`.
    - We can submit the form by changing `toVersion`. In addition to asserting that we see the correct select option, assert that `@onSubmit` is called and receives the new values of `fromVersion` and `toVersion`.

## References

- [Tests for `<SearchForm>` in whats-new-in-emberland](https://github.com/ember-learn/whats-new-in-emberland/blob/master/tests/integration/components/search-form-test.js)

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by jpsanantonio** [comment]
Hi @ijlee2 , I'd like to work on this. Can I pick this up?

**Comment by ijlee2** [comment]
@jpsanantonio Yep, thank you for taking an interest in this project!
