### ISSUE TITLE
Store Ember versions in a utility file

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#46]
## Background

The app automatically creates the select options for `Ember Versions` form. It does so by reading Ember versions from an array of strings.

<img width="240" alt="ember-versions-form component" src="https://user-images.githubusercontent.com/16869656/94374412-acab3b80-00d1-11eb-96ba-c51c0ed2b971.png">

## Problem

The aforementioned array lives in `app/models` directory, even though it is not an Ember Data model. Let's move the array to `app/utils`.

## TODOs

- [ ] Use Ember CLI to generate a utility called `ember-versions`. You can delete the unit test file.

- [ ] Copy-paste the export statement in `app/models/versions.js` to the utility file.

- [ ] Update the import statements to read from the utility instead.

- [ ] Remove `app/models/versions.js`.

- [ ] Update [README](https://github.com/ember-learn/upgrade-guide#adding-the-latest-ember-version) to document where `VERSIONS` array can be found now.

- [ ] Audit all Ember versions in `VERSIONS` array. (There are some versions that will result in an error when we select them.) Please list these versions in your pull request so that we can create a follow-up issue!

**Comment by Pustur** [comment]
Seems easy enough, I'll do this as well 🙂

**Comment by ijlee2** [comment]
Hi, @Pustur. I appreciate your energy in helping out with Ember repos!

I want to make sure that there are enough issues for many people to work on during Hacktoberfest and the upcoming EmberFest workshop. (Coming up with an issue and writing it up is not easy...)

Let me ask you to work on #50 for now. If no one else can volunteer for this issue, I will ping you to see if you can still help!

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!
