### ISSUE TITLE
Simplify <ListFeaturesDeprecations> component

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#47]
## Background

The `<ListFeaturesDeprecations>` component shows features and deprecations that were added between `fromVersion` and `toVersion`. It does so by transforming `@datum` into `this.model` (both are an array of POJOs).

Note that `@datum` includes changes to Ember.js, Ember Data, and Ember CLI for _all_ versions, whereas `this.model` only includes changes between `fromVersion` and `toVersion`.

## Problem

First, the variable names `@datum` and `model` aren't descriptive. This makes maintenance and onboarding new contributors difficult.

We can also simplify the component and the base model class `app/models/private/-common.js` if we alter the data structure of `this.model`.

## TODOs

- [ ] Rename the argument `@datum` to `@allChangeLogs`. (Each element in the array corresponds to an Ember version.) Update the rendering tests for `<ListFeaturesDeprecations>` so that they may pass again.

    <details>
    <summary>An example of <code>allChangeLogs</code></summary>

    ```javascript
    allChangeLogs = [
      {
        version: '2.18',
        changes: [
          {
            feature: true,
            title: 'Feature #1',
            link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
          },
          {
            deprecation: true,
            title: 'Deprecation #1',
            link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
          },
          {
            deprecation: true,
            title: 'Deprecation #2',
            link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
          },
        ],
      },
      {
        version: '3.0',
        changes: [],
      },
      {
        version: '3.1',
        changes: [
          {
            feature: true,
            title: 'Feature #1',
            link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
          },
          {
            feature: true,
            title: 'Feature #2',
            link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
          },
          {
            deprecation: true,
            title: 'Deprecation #1',
            link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
          },
        ],
      },
    ];
    ```

    </details>

- [ ] Rename the computed-getter `model` to `relevantChangeLogs`.

- [ ] Created a computed-getter called `features`. The getter should reduce the array `relevantChangeLogs` by keeping the features only. It also adds the Ember version to each object.

    <details>
    <summary>Expected output for the example above</summary>

    ```javascript
    features = [
      {
        title: 'Feature #1',
        link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
        version: '2.18',
      },
      {
        title: 'Feature #1',
        link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
        version: '3.1',
      },
      {
        title: 'Feature #2',
        link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
        version: '3.1',
      },
    ];
    ```

    </details>

- [ ] Created a computed-getter called `deprecations`. The getter should reduce the array `relevantChangeLogs` by keeping the deprecations only. It also adds the Ember version to each object.

    <details>
    <summary>Expected output for the example above</summary>

    ```javascript
    deprecations = [
      {
        title: 'Deprecation #1',
        link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
        version: '2.18',
      },
      {
        title: 'Deprecation #2',
        link: 'https://blog.emberjs.com/2018/01/01/ember-2-18-released.html',
        version: '2.18',
      },
      {
        title: 'Deprecation #1',
        link: 'https://blog.emberjs.com/2018/02/16/ember-3-1-beta-released.html',
        version: '3.1',
      },
    ];
    ```

    </details>

- [ ] Use `this.features` and `this.deprecations` to simplify the component template.

    <details>
    <summary>Hint</summary>

    ```handlebars
    {{!-- Before --}}
    {{#each this.model as |model|}}
      {{#each model.changes as |change|}}
        {{#if change.feature}}
          <li>...</li>
        {{/if}}
      {{/each}}
    {{/each}}

    {{!-- After --}}
    {{#each this.features as |feature|}}
      <li>...</li>
    {{/each}}
    ```

    </details>
 
- [ ] Remove the count getters from the component and base model.

    - `countOfFeatureChanges`
    - `countOfDeprecationChanges`
    - `featuresCount`
    - `deprecationsCount`

    Don't forget to remove `featuresCount` and `deprecationsCount` from `tests/integration/components/list-features-deprecations-test.js`. ✨

## References

- [MDN - Array.prototype.reduce()](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

**Comment by Pustur** [comment]
I'll take this as well why not

**Comment by ijlee2** [comment]
Hi, @Pustur. I appreciate your energy in helping out with Ember repos!

I want to make sure that there are enough issues for many people to work on during Hacktoberfest and the upcoming EmberFest workshop. (Coming up with an issue and writing it up is not easy...)

Let me ask you to work on #50 for now. If no one else can volunteer for this issue, I will ping you to see if you can still help!

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by Pustur** [comment]
No problem, I absolutely understand. Sorry for trying to steal all the (very well written BTW) issues 😅  
Happy Hacktoberfest everyone 🎉

**Comment by ijlee2** [comment]
Haha, you're good. I'm glad to see early responses from people!

**Comment by mgoetzke** [comment]
Hey @ijlee2, I'd be interested in working on this!

**Comment by ijlee2** [comment]
Thanks, @mgoetzke ! To help with review, will you make a commit after each step? Let us know if you have any questions.

**Comment by ijlee2** [comment]
Hi, @mgoetzke. I merged a pull request that may likely affect this issue. Will you rebase your branch so that you are working with the latest code?

I think the commands are:

```bash
# Check out the default branch
git checkout master

# Set upstream
git remote set upstream git@github.com:ember-learn/upgrade-guide.git

# Check if upstream was set correctly (you will see 2 lines of output for origin, and another 2 lines for upstream)
git remote -v

# Get the latest branches and code
git fetch upstream
git merge upstream/master
git push origin master

# Rebase your branch
git checkout <your-branch-name>
git pull --rebase origin master
```
