### ISSUE TITLE
Separate form and search results (Part 1 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#48]
## Background

The `<select>` elements in `Ember Versions` form might be considered a jump menu (see [code](https://github.com/ember-learn/upgrade-guide/blob/45794a45e6676e7598f12e4b47a6cdd151b17149/app/templates/index.hbs#L4-L45)).

A **jump menu** is a `<select>` that triggers page changes when a (sighted) user clicks an option with a mouse. When a (non-sighted) user navigates with a keyboard, browsing the options triggers page changes, which can cause confusion.

For example, in our app, as soon as the user types `2` (to search for 2.18), the app would find the first option that starts with `2`, which is `2.0 Beta`, then display features and deprecations for this version.

According to [WebAIM](https://webaim.org/techniques/forms/controls#javascript) and [Penn State University](https://accessibility.psu.edu/formshtml/), we should try to avoid jump menus and favor having a submit button in the form.

## Problem

Please wait till #45 and #47 have been completed and merged.

The `changes` route shows features and deprecations that were added between `fromVersion` and `toVersion`. It also shows a link to go back to the `index` route.

### Part 1: Create `changes` route

- [ ] Use Ember CLI to create the `changes` route. Copy-paste the [template code](https://github.com/ember-learn/upgrade-guide/blob/45794a45e6676e7598f12e4b47a6cdd151b17149/app/templates/index.hbs#L48-L78) from `index.hbs` to `changes.hbs`. Elevate the heading level for `Upgrading from {{this.fromVersion}} to {{this.toVersion}}` to `<h1>`.

    <details>
    <summary>Hint</summary>

    If we visit [localhost:4200/changes](http://localhost:4200/changes), we should see the header `Upgrading from to`. We don't see any features or deprecations for Ember.js, Ember Data, and Ember CLI.

    </details>

- [ ] Use Ember CLI to create the `changes` controller. By default, the query parameters `fromVersion` and `toVersion` take on the values `3.15` and the last element in the `VERSIONS` array. (Copy-paste from the `index` controller.)

    <details>
    <summary>Hint</summary>

    If we visit [localhost:4200/changes](http://localhost:4200/changes), we should see the header `Upgrading from 3.15 to 3.21`. We don't see any features or deprecations for Ember.js, Ember Data, and Ember CLI.

    </details>

- [ ] Copy-paste the `model` hook from the `index` route to `changes` route.

    <details>
    <summary>Hint</summary>

    If we visit [localhost:4200/changes](http://localhost:4200/changes), we should now see features and deprecations that were added to Ember.js, Ember Data, and Ember CLI between 3.15 (exclusive) and 3.21 (inclusive).

    </details>

- [ ] In `changes.hbs`, add a link to go back to the `index` route. Assign the label `Return to Homepage` and test selector `data-test-link="Return to Homepage"`.

- [ ] Write application tests to describe what a user can do in the `changes` route. Please write tests to check the following:

    - `tests/acceptance/changes-test.js`
        - When we visit the changes route without query parameters, we see the features and deprecations that occurred since version 3.15
        - When we visit the changes route with query parameters, we see the features and deprecations that occurred between fromVersion and toVersion
        - When we click the Return to Homepage button, we are redirected to the index route

## References

- [Application tests for in whats-new-in-emberland](https://github.com/ember-learn/whats-new-in-emberland/blob/master/tests/acceptance/pull-requests-test.js)

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by jpsanantonio** [comment]
Hi @ijlee2 , I'd like to help with this issue. Is it okay if I pick this up? :)

**Comment by ijlee2** [comment]
@jpsanantonio Yep, thank you!
