### ISSUE TITLE
Upgrade app to Ember 3.21

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#50]
## Problem

If you run `npm outdated`, you will see that many packages can use an update. At the time of writing, I saw,

```bash
❯ npm outdated

Package                     Current    Wanted  Latest  Location
@ember/optional-features      1.3.0     1.3.0   2.0.0  upgrade-guide
@glimmer/component            1.0.0     1.0.2   1.0.2  upgrade-guide
@glimmer/tracking             1.0.0     1.0.2   1.0.2  upgrade-guide
broccoli-static-site-json     4.1.0     4.2.1   4.2.1  upgrade-guide
ember-auto-import             1.5.3     1.6.0   1.6.0  upgrade-guide
ember-cli                    3.18.0    3.18.0  3.21.2  upgrade-guide
ember-cli-babel              7.20.0    7.22.1  7.22.1  upgrade-guide
ember-cli-htmlbars            4.3.1     4.4.0   5.3.1  upgrade-guide
ember-data                   3.18.0    3.18.0  3.21.2  upgrade-guide
ember-fetch                   8.0.1     8.0.2   8.0.2  upgrade-guide
ember-resolver                8.0.0     8.0.2   8.0.2  upgrade-guide
ember-source                 3.18.1    3.18.1  3.21.1  upgrade-guide
ember-styleguide           4.0.0-13  4.0.0-13   5.0.0  upgrade-guide
ember-template-lint           2.7.0    2.13.0  2.13.0  upgrade-guide
eslint                        6.8.0     6.8.0  7.10.0  upgrade-guide
eslint-config-prettier       6.11.0    6.12.0  6.12.0  upgrade-guide
eslint-plugin-ember           8.5.1    8.14.0   9.1.0  upgrade-guide
eslint-plugin-prettier        3.1.3     3.1.4   3.1.4  upgrade-guide
prettier                      2.0.5     2.1.2   2.1.2  upgrade-guide
```

Moreover, the `cli-guides` app currently uses Ember `v3.18.1`. Let's upgrade the app to `v3.21.x` (or `v3.22.x` if it is available) for a regular maintenance.

## TODOs

I may recommend updating packages in batches as shown below. (Hopefully, no major release introduced a breaking change that affects this app.)

After each batch update of packages, please push a commit so that the CI may check that lints and tests continue to pass.

- [ ] Update lint/test-related packages
  - ember-template-lint
  - eslint
  - eslint-config-prettier
  - eslint-plugin-ember
  - eslint-plugin-prettier
  - prettier

- [ ] Update Ember addons
  - broccoli-static-site-json
  - ember-styleguide

- [ ] Update Ember-related packages (packages installed by default)
  - @ember/optional-features
  - @glimmer/component
  - @glimmer/tracking
  - ember-auto-import
  - ember-cli-babel
  - ember-cli-htmlbars
  - Remove ember-cli-uglify, then install ember-cli-terser
  - ember-fetch
  - ember-resolver

- [ ] Update Ember with `ember-cli-update`
  - ember-cli
  - ember-data
  - ember-source

**Comment by Pustur** [comment]
I'd like to help with this, can you assign me?

**Comment by ijlee2** [comment]
Hi, @Pustur. Thanks for taking an interest in helping out with this issue! Yep, I can assign the issue to you to work on.

I created the issue for [Hacktoberfest](https://hacktoberfest.digitalocean.com/), which will begin in 3 days. If you wanted to participate in the event, would you like to wait on working on a solution until October 1st?

In the meantime, I'd suggest trying out:

- Cloning the repo
- Running the Ember app locally to see if you can use the select options to find features and deprecations

Trying out these steps would help us discover early issues a new contributor might face during Hacktoberfest. ✨

**Comment by Pustur** [comment]
Hey @ijlee2, 

I cloned the repo, I'm able to `npm install` without problems and I can serve the app locally. Tests run succesfully.  
I'm currently using node `12.18.3`, let me know if I should use another version.

I'll wait until october 1st before submitting a PR.

**Comment by ijlee2** [comment]
Great, glad to hear that everything went well! Since you are using the latest v12 Node, I think you'll be okay.
